### ISSUE TITLE
(not urgent) truncateNP appears to be memory bottleneck

### ISSUE THREAD

**Issue by e-t-k** [Stuartlab-UCSC/hexmap-data#5]
https://github.com/ucscHexmap/compute/blob/40d7b8a8c57213e03979b91b12d6f78958788435/calc/compute_sparse_matrix.py#L363

I was calculating a larger tumorMap than I have before ( `CKCC/combined_GTEX_v7`, 19k samples by 24k genes)  and I got a MemoryError during the truncateNP call; traceback below.

Since its purpose appears to be consistency on different machines and it doesn't substantially alter the result of the calculation, I commented out that line, and `layout.py` then ran to completion & generated a reasonable-looking tumorMap.

Wanted to bring this to your attention in case there's an easy fix, but right now it's not a problem for me since I'm satisfied with the workaround, so no urgency.

```
Traceback (most recent call last):
  File "compute-prod-2018-07-18/calc/layout.py", line 1866, in <module>
    sys.exit(main(sys.argv[1:]))
  File "compute-prod-2018-07-18/calc/layout.py", line 1864, in main
    makeMapUIfiles(arg_obj, args)
  File "compute-prod-2018-07-18/calc/layout.py", line 1405, in makeMapUIfiles
    log=None
  File "/data/data/featureSpace/CKCC/combined_GTEX_v7/compute-prod-2018-07-18/calc/compute_sparse_matrix.py", line 363, in compute_similarities
    x_corr = truncateNP(x_corr,11)
  File "/data/env/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2755, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/data/env/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2831, in _vectorize_call
    outputs = ufunc(*inputs)
  File "/data/data/featureSpace/CKCC/combined_GTEX_v7/compute-prod-2018-07-18/calc/utils.py", line 200, in truncate
    return '.'.join([i, (d+'0'*n)[:n]])
MemoryError
```

**Comment by terraswat** [comment]
Thank you for bringing this to our attention! Apparently you hit the magic sized matrix to trigger this error. It's been fixed and so you can use our code base again.

Best,
Teresa
